### ISSUE TITLE
See list of current bills to vote on

### ISSUE THREAD

**Issue by dsernst** [liquidvote/liquid-ios#5]
This issue is to track the MVP feature to see current voteable legislation for your jurisdictions.

**Comment by dsernst** [comment]
This depends upon this accompanying API endpoint: https://github.com/Crowdocracy/liquid-api/issues/1

**Comment by dsernst** [comment]
See this comment for a proposed mockup of how this could look: https://github.com/Crowdocracy/liquid-ios/issues/3#issuecomment-241306873

**Comment by dsernst** [comment]
Would also be very powerful to see the current electorate's standing on each issue. "Right now the vote is 70/30".

**Comment by jaredscheib** [comment]
On principle I'd like to give as much info as possible (such as the current network leaning of 70/30), but there's a part of me that wants to keep the legislation plain at this overview level – or something to encourage people to vote based on the merits of legislation alone, rather than being influenced by social effects.

**Comment by jaredscheib** [comment]
That being said, I like the mockup above as a start.

What are Info and Invite?

And, should this view include a means of voting? Maybe something like the Facebook "Like" button that, when held, allows for the 6 reactions, and in this case Yes / No / Abstain / Delegate ?

**Comment by dsernst** [comment]
See https://github.com/liquidvote/liquid-ios/issues/3#issuecomment-238987348 for description of Info and Invite.

**Comment by dsernst** [comment]
And yes to your final question, you could edit your vote from this screen.

**Comment by dsernst** [comment]
Made some serious progress on this front. These are the SF Ballot Measures for this upcoming November 8, 2016 election in SF. You can press on one to get more info about it.

![screen shot 2016-10-05 at 4 57 40 am](https://cloud.githubusercontent.com/assets/6340841/19112202/6b4a2c70-8ab8-11e6-9d06-d38c7e9b44e4.png)

**Comment by dsernst** [comment]
This is blocked on not having APIs to display federal, state, and city legislation.
