### ISSUE TITLE
Set delegates

### ISSUE THREAD

**Issue by dsernst** [liquidvote/liquid-ios#6]
This issue is to track the MVP feature to assign and update your current delegates.

**Comment by dsernst** [comment]
I imagine the selection starts with a search box `Search for people by name, email, or phone number`:
  - It auto-completes based on already registered users, but you can enter someone's email or phone number if they haven't registered yet (like Venmo).
  - The list of search results shows a profile picture, their name, and a number showing how many people have delegated to them.

**Comment by dsernst** [comment]
Other ways one could find new delegates:
- your Facebook contacts
- a public twitter page
- popular people within the system (leaderboard for your jurisdiction)
  - This could have significant implications on power distribution.
  - On one hand, it makes it easier for new users to get started by making it easy for them to see already popular choices. 
  - It also creates a very clear social reward for being in the top leaderboard, making people compete to get and stay on there.
  - On the other hand, it makes it much more likely that the already powerful become even more powerful.

**Comment by jaredscheib** [comment]
Could also consider handles or hashes. Makes me think of layering on profiles à la a social network, being able to browse for delegates, learn about them, etc.

**Comment by dsernst** [comment]
This is a little weird to do right now because there are so few users in the system it's hard to really look anyone up. Maybe one approach would be to select people via your phone's Contacts list.

**Comment by dsernst** [comment]
All of these look like they could be leveraged to access the device's contacts:

1. https://github.com/rt2zz/react-native-contacts
2. https://github.com/LynxITDigital/react-native-contacts-wrapper
3. https://github.com/joshuapinter/react-native-unified-contacts
4. https://github.com/rt2zz/react-native-addressbook
5. https://github.com/mattotodd/react-native-addressbook-ios

Listed in order of most promising to least.

**Comment by dsernst** [comment]
See https://github.com/liquidvote/blog/issues/3 for example text that could be used on this page.
