### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by dsernst** [liquidvote/liquid-ios#7]
A basic page to type in your email address. Front-end for https://github.com/Crowdocracy/liquid-api/issues/10

**Comment by dsernst** [comment]
First draft mockup:

<img width="1112" alt="screen shot 2016-09-16 at 5 01 54 pm" src="https://cloud.githubusercontent.com/assets/6340841/18604286/a873c896-7c2f-11e6-9e1c-c5759468feb5.png">

**Comment by jaredscheib** [comment]
Looks great -- nice work! Let me know where you put that asset, or add it
to the repo, and I'll integrate it when I get to this. Thanks!

**Comment by dsernst** [comment]
Another iteration, including a "waiting list" page:

<img width="1298" alt="screen shot 2016-09-19 at 10 02 26 pm" src="https://cloud.githubusercontent.com/assets/6340841/18658094/ed3fe518-7eb4-11e6-856a-3b1470204c21.png">

And a dark version:

<img width="460" alt="screen shot 2016-09-19 at 10 02 38 pm" src="https://cloud.githubusercontent.com/assets/6340841/18658143/fbc081c4-7eb4-11e6-9ef7-6f7a269da431.png">

**Comment by dsernst** [comment]
- [x] As of https://github.com/liquidvote/liquid-ios/commit/38b122d8dcf3fe780b25856d9f77a0848eb6824d, the structure and styling for this is all done now.
- [ ] Went with light version but would like to try dark version.
- [x] https://github.com/liquidvote/liquid-ios/commit/ce354e52c3dfe3bda73912ba054fc9fb4b1b4f5a Hooked up the Waiting List page to actually fetch the latest number of voters (unique emails in db) from https://api.liquid.vote/voters `X-Total-Count` header 
- [ ] Need to hook up the Login page to actually post to https://api.liquid.vote/

**Comment by dsernst** [comment]
Here's a live screenshot of the opening page:

<img src="https://cloud.githubusercontent.com/assets/6340841/18907610/21ed6ea8-8521-11e6-9b4a-8aad96e71b52.png" width="375" />
